### ISSUE TITLE
NODE_ENV configuration is missing in webpack

### ISSUE THREAD

**Issue by jhonnymichel** [kaueburiti/kaueburiti.github.io#1]
`plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify('production')
      }
    })
  ]`

Don't forget to add this when you're ready to release it... React code will be way smaller and perform better cause it'll throw all the debug and testing away.

**Comment by kaueburiti** [comment]
Hello sr, I will close this issue. Thank you for the tip.
